name: CS519Project
channels:
- pytorch 
- dglteam
- conda-forge
- fragcolor
- anaconda
- defaults
dependencies:
- cudnn
- python-dateutil
- pillow
- dgl
- numpy
- matplotlib
- tensorboard
- tensorboardx
- future
- absl-py
- networkx
- scikit-learn
- scipy
- notebook
- h5py
- mkl
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- plotly
- scikit-image
- requests
- tqdm
- tensorflow-gpu
- tensorflow-estimator
- tensorboard